const TABLET_MIN_WIDTH = 768;
const DESKTOP_MIN_WIDTH = 1024;
const DEFAULT_CARD_COLOR = '#ffffff';
const SHOWN_NAV_ITEM_ID = 'courses';

export {TABLET_MIN_WIDTH, DESKTOP_MIN_WIDTH, DEFAULT_CARD_COLOR, SHOWN_NAV_ITEM_ID};
